# This is a basic workflow to help you get started with Actions

name: Run the url_watcher script

# Controls when the action will run.
on:
  schedule:
    - cron: 0 * * * *

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CheckForUpdates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute the script
        run: python3 url_watcher.py
